name: Pull request validation

on:
  pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip3 install --use-feature=2020-resolver -e '.[dev]'
    - name: Run tests and linters
      run: |
        python3 -m black naas_drivers
        python3 -m flake8 naas_drivers
    - name: Validate PR title with commitizen
      uses: CashStory/commitizen-action-pr@1.0.1
